name: foxlearn
description: An Education Series of  Flutter Apps
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.3
  flutter_svg: ^0.18.1
  catcher: ^0.4.2
  moor_flutter: ^3.1.0
  moor_inspector: ^0.1.3
  lottie: any
  get_storage: any
  sizer: ^1.1.8
  device_preview: any
  tuple: ^1.0.3
  flutter_windowmanager: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  moor_generator: ^3.4.1

flutter:

  uses-material-design: true
  fonts:
    - family: sst-arabic
      fonts:
        - asset:  assets/fonts/sst-arabic-bold.ttf
        - asset:  assets/fonts/sst-arabic-light.ttf
        - asset:  assets/fonts/sst-arabic-medium.ttf
        - asset:  assets/fonts/sst-arabic-roman.ttf


