name: foxlearn
description: An Education Series of  Flutter Apps
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.1.4
  flutter_svg: ^0.21.0+1
  catcher: ^0.6.5
  moor_flutter: ^4.0.0
  moor_inspector: ^0.2.0
  lottie: ^1.0.1
  get_storage: ^2.0.2
  responsive_sizer: ^2.0.0+1
  tuple: ^2.0.0
  language_pickers: ^0.2.0+1
  flutter_hooks: ^0.16.0
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.0.3
  mdi: ^4.0.0
  expandable: ^4.1.4
  flutter_phoenix: "^0.1.0"
  get_it: ^6.1.1
  flutter_bloc: ^7.0.0
  bot_toast: ^4.0.1
  equatable: ^2.0.0
  flutter_native_splash: ^1.1.8+4
  firebase_core: ^1.1.0
  firebase_messaging: ^9.1.3
  internet_connection_checker: ^0.0.1
  expansion_tile_card: ^2.0.0
  bouncing_widget: ^2.0.0
  custom_navigation_bar: ^0.8.1
  fluttericon: ^2.0.0
  eva_icons_flutter: ^3.0.0
  line_awesome_flutter: ^1.1.0-nullsafety
  percent_indicator: ^3.0.1
  sleek_circular_slider: ^2.0.0
  flip_card: ^0.5.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.2.1
  freezed: ^0.14.1+2
  build_runner:  ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/lotti/
    - assets/svg/
    - images/
    - assets/logo/
    - assets/png/
  fonts:
    - family: sst-arabic
      fonts:
        - asset:  assets/fonts/sst-arabic-bold.ttf
        - asset:  assets/fonts/sst-arabic-light.ttf
        - asset:  assets/fonts/sst-arabic-medium.ttf
        - asset:  assets/fonts/sst-arabic-roman.ttf


